#!/bin/bash

# the very first line is a special directive for Bash shell, do not remove
# lines that start with "#SBATCH" are special directives for Slurm
# other lines that start with "#" are comments

#SBATCH --job-name=test_torch_env      ## job name
#SBATCH -p atlas                       ## use free partition
#SBATCH --nodes=1                      ## use 1 node, don't ask for multiple
#SBATCH --ntasks=1                     ## ask for 1 CPU
#SBATCH --mem-per-cpu=1G               ## ask for 1Gb memory per CPU
#SBATCH --error=%x.%A.err              ## Slurm error  file, %x - job name, %A job id
#SBATCH --out=%x.%A.out                ## Slurm output file, %x - job name, %A job id

# Run command hostname and assign output to a variable
hn=`hostname`
echo "Running job on host $hn"

# load modules
ml purge
ml miniconda/3

# Activate conda env
conda activate piad

# Run python code
python test.py
